version: '3'

services:
  mirror:
    image: ghcr.io/eugenmayer/nist-data-mirror:latest
    ports:
      - 80:80
    volumes:
      - data:/usr/local/apache2/htdocs

volumes:
  data:
    driver: local
