apiVersion: v1
kind: Service
metadata:
  name: {{ template "nist-data-mirror.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nist-data-mirror.name" . }}
    helm.sh/chart: {{ include "nist-data-mirror.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nist-data-mirror.name" . }}
